spring:
  datasource:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  jwt:
    secret:

  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static:
      s3:
        bucket:
      stack:
        auto: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    redis:
      host:
      port:

server:
  forward-headers-strategy: framework # Swagger에서 https 요청이 나가도록 하기 위함