spring:
  datasource:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  jwt:
    secret:
  data:
    redis:
      host: localhost
      port: 6379