spring:
  datasource:
    url:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

print-stack-trace: true