package com.project.trainingdiary.model.type;

public enum NotificationType {

  RESERVATION_APPLIED,
  RESERVATION_ACCEPTED,
  RESERVATION_REJECTED,
  RESERVATION_CANCELLED_BY_TRAINER,
  RESERVATION_CANCELLED_BY_TRAINEE,
  RESERVATION_REGISTERED,
  PT_CONTRACT_CREATED,
  ONE_HOUR_BEFORE_PT_SESSION
}